### ISSUE TITLE
possible to get local ip

### ISSUE THREAD

**Issue by kodeine** [otalk/RTCPeerConnection#102]
is it possible to get local ip using this rtc library?

**Comment by fippo** [comment]
it will show up in the 'ice' event.

But if you're trying to use webrtc for fingerprinting you're in for a surprise soon :-p

**Comment by kodeine** [comment]
Well now you've got me all excited, do you have any example for fingerprinting? I'm new to exploring webrtc.

**Comment by kodeine** [comment]
Did you mean media device IDs or am I going to be surprised more lol

**Comment by fippo** [comment]
there are various stackoverflow posts explaining how it works.
