### ISSUE TITLE
Hook for modifying offer/answer before setting it locally and sending

### ISSUE THREAD

**Issue by RangerMauve** [otalk/RTCPeerConnection#11]
Is there something I can hook into to modify the SDP settings before they get set as the local description and sent as the offer/answer?

**Comment by prerakjain** [comment]
@fippo When will you commit the final changes for this issue. I am also looking for some way to modify the SDP parameters using RTCPeerConnection.

**Comment by fippo** [comment]
I've abandoned this approach in favor of passing custom optional constraints. Which is actually to how the w3c group thinks it should work and I agree.

**Comment by RangerMauve** [comment]
Might be a good idea to close this issue, then.

**Comment by prerakjain** [comment]
One more question, do you have any APIs I can use to set these optional constraints to modify SDP.
