### ISSUE TITLE
Firefox issue when _onIce called

### ISSUE THREAD

**Issue by sarumjanuch** [otalk/RTCPeerConnection#38]
Hi Guys, i am using your cool stanza.io, and during filetransfer testing i find out that it is not working between Chrome and Firefox, and during investigation i came to the point that issue is in rtcpeerconnection (we all know that issue is in Firefox) but nevertheless: 
<pre>
if (!ice.sdpMid) { // firefox doesn't set this
    ice.sdpMid = self.localDescription.contents[ice.sdpMLineIndex].name;
}
</pre>
settings sdpMid to"data", then goes: <pre> if (!self.config.ice[ice.sdpMid]) </pre>, which must fix everything, but <pre>SJJ.toSessionJSON(self.pc.localDescription.sdp, bla bla bla</pre> parse m=, and setting content to application, we end's up with the situation where ice.sdpMid = "data", but self.config.ice have only "application" key, and this cause to fail next code: 
<pre>                       
ufrag: self.config.ice[ice.sdpMid].ufrag,
pwd: self.config.ice[ice.sdpMid].pwd,
</pre>
with: "TypeError: self.config.ice[ice.sdpMid] is undefined". 
Any ideas how to fix this? If i can somehow help you just let me know. I am not an WebRTC expert so i can only guessing what is going on here. Thank you very much for attention.

**Comment by fippo** [comment]
Firefox 35 (and probably the current 36) has a more-or-less known bug (nobody can point me to an bugzilla issue number) where it generates candidates before the localdescription is set.

This sounds a rather unexpected followup from that... @legastero thoughts?

**Comment by sarumjanuch** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1087551 I belive this one.

**Comment by fippo** [comment]
It only happens in interop between Chrome and Firefox? Who's sending the file / creating the offer?

Does it also happen with https://github.com/legastero/jingle-interop-demos/tree/gh-pages/stanzaio (even though that code is a little rusty)

I think I know what the problem is...

**Comment by sarumjanuch** [comment]
Only Chrome to Chrome works. Chrome to FF don't work, also when trying to send from FF i get: self.localDescription.contents[ice.sdpMLineIndex] is undefined. So no way to test other scenarios. I have tested it here: http://code.gar.zone/?gist=8e0436e22e09ce74310c, and then get same result on my local servers.
