### ISSUE TITLE
Screen stream from firefox to chrome

### ISSUE THREAD

**Issue by avenger86** [otalk/RTCPeerConnection#56]
When i try to add screen share stream to established peer connection(with audio and video data), from firefox to chrome, on the chrome side i have an erorr: "Failed to initialize the answer".
Offer that chrome receive is :
"v=0
↵o=mozilla...THIS_IS_SDPARTA-42.0 1756619254475437899 1 IN IP4 0.0.0.0
↵s=-
↵t=0 0
↵a=fingerprint:sha-256 17:CC:6A:29:61:D5:8B:77:A7:24:D3:BA:D9:DD:01:B9:C7:9E:0A:4E:42:48:6C:36:EF:46:9D:2C:FC:51:6A:A5
↵a=group:BUNDLE sdparta_0 sdparta_1 sdparta_2
↵a=ice-options:trickle
↵a=msid-semantic:WMS *
↵m=audio 54693 RTP/SAVPF 109 9 0 8
↵c=IN IP4 206.54.171.168
↵a=candidate:0 1 UDP 2122252543 192.168.1.11 61907 typ host
↵a=candidate:1 1 UDP 1686052863 195.88.113.136 61907 typ srflx raddr 192.168.1.11 rport 61907
↵a=candidate:2 1 UDP 92217343 206.54.171.168 54693 typ relay raddr 206.54.171.168 rport 54693
↵a=sendrecv
↵a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
↵a=ice-pwd:e3d38d1f3271f1922b53ee3a0c329aaf
↵a=ice-ufrag:970059ba
↵a=mid:sdparta_0
↵a=msid:{06639e53-45f3-42a8-a6cc-644778c6d471} {d6ad0fcd-f160-4752-a2de-c061afd5ab75}
↵a=rtcp-mux
↵a=rtpmap:109 opus/48000/2
↵a=rtpmap:9 G722/8000/1
↵a=rtpmap:0 PCMU/8000
↵a=rtpmap:8 PCMA/8000
↵a=setup:actpass
↵a=ssrc:3934791550 cname:{9af297ab-4ada-47d2-81e4-919931391eb6}
↵m=video 9 RTP/SAVPF 120 126 97
↵c=IN IP4 0.0.0.0
↵a=sendrecv
↵a=fmtp:120 max-fs=12288;max-fr=60
↵a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
↵a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
↵a=ice-pwd:e3d38d1f3271f1922b53ee3a0c329aaf
↵a=ice-ufrag:970059ba
↵a=mid:sdparta_1
↵a=msid:{06639e53-45f3-42a8-a6cc-644778c6d471} {07fc56ab-4378-4012-b009-1b12c1992ba9}
↵a=rtcp-fb:120 nack
↵a=rtcp-fb:120 nack pli
↵a=rtcp-fb:120 ccm fir
↵a=rtcp-fb:126 nack
↵a=rtcp-fb:126 nack pli
↵a=rtcp-fb:126 ccm fir
↵a=rtcp-fb:97 nack
↵a=rtcp-fb:97 nack pli
↵a=rtcp-fb:97 ccm fir
↵a=rtcp-mux
↵a=rtpmap:120 VP8/90000
↵a=rtpmap:126 H264/90000
↵a=rtpmap:97 H264/90000
↵a=setup:actpass
↵a=ssrc:3229964890 cname:{9af297ab-4ada-47d2-81e4-919931391eb6}
↵m=video 9 RTP/SAVPF 120 126 97
↵c=IN IP4 0.0.0.0
↵a=bundle-only
↵a=sendonly
↵a=fmtp:120 max-fs=12288;max-fr=60
↵a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
↵a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
↵a=ice-pwd:e3d38d1f3271f1922b53ee3a0c329aaf
↵a=ice-ufrag:970059ba
↵a=mid:sdparta_2
↵a=msid:{3f4c297b-50e3-4f4b-b350-37de1be1c469} {a36a8f86-51a5-4a39-a115-4bc669d2b8d4}
↵a=rtcp-fb:120 nack
↵a=rtcp-fb:120 nack pli
↵a=rtcp-fb:120 ccm fir
↵a=rtcp-fb:126 nack
↵a=rtcp-fb:126 nack pli
↵a=rtcp-fb:126 ccm fir
↵a=rtcp-fb:97 nack
↵a=rtcp-fb:97 nack pli
↵a=rtcp-fb:97 ccm fir
↵a=rtcp-mux
↵a=rtpmap:120 VP8/90000
↵a=rtpmap:126 H264/90000
↵a=rtpmap:97 H264/90000
↵a=setup:actpass
↵a=ssrc:3162226236 cname:{9af297ab-4ada-47d2-81e4-919931391eb6}
↵"
In other combinations of browsers all is ok.

**Comment by fippo** [comment]
Firefox and Chrome currently implement different ways to do multiple streams and are not compatible with each other.

**Comment by avenger86** [comment]
Thank you for answer. Although the previous version of Chromium everything worked as it should
