### ISSUE TITLE
Firefox: "Mandatory/optional in createOffer options no longer works!"

### ISSUE THREAD

**Issue by robbie-c** [otalk/RTCPeerConnection#60]
Code to reproduce:
```javascript
var pc = new RTCPeerConnection({
  iceServers: [
    {
      urls: 'stun:stun.l.google.com:19302'
    }
  ]
});
pc.offer(function(err, offer) {
  console.log(err);
});
```

Console output:
```
Mandatory/optional in createOffer options no longer works! Use {"offerToReceiveAudio":true,"offerToReceiveVideo":true} instead (note the case difference)! <unknown>
DOMException [InternalError: "Cannot create an offer with no local tracks, no offerToReceiveAudio/Video, and no DataChannel."
code: 0
nsresult: 0x0]
```

Can we catch that exception in createOffer, create a new constraints object that FF will support, and try again?

**Comment by fippo** [comment]
hrm. I think the right thing to do here is to upgrade the constraints to the new format. 
Which is tricky for answers though since IIIRC Firefox doesn't do answer constraints...

**Comment by fippo** [comment]
what Firefox version are you using? I haven't seen anything in the changelogs indicating such a change?

**Comment by robbie-c** [comment]
This is 43.0, full build string:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by robbie-c** [comment]
Relevant https://bugzilla.mozilla.org/show_bug.cgi?id=1064223

**Comment by fippo** [comment]
yep, just found that as well. It wasn't in the tl;dr @ https://groups.google.com/d/msgid/discuss-webrtc/560E9E3B.2080403%40reavy.org?utm_medium=email&utm_source=footer

**Comment by robbie-c** [comment]
It seems like Chrome supports the  `{ offerToReceiveVideo: 1, offerToReceiveAudio: 1 }` syntax for `createOffer` but not for `createAnswer`. I modified the jsfiddle on the bugzilla page to show this: https://jsfiddle.net/z685gt38/

**Comment by fippo** [comment]
yeah. IIRC using this for answer options is non-standard. Should probably be removed here but that is a major version bump :-/

**Comment by robbie-c** [comment]
Would you be interested in a PR that converts the constraints, so the user can use either format for both function calls?

**Comment by fippo** [comment]
that should be done in https://github.com/webrtc/adapter -- but the old format is really obsolete now so I don't think converting the now-spec constraints is something that should be done in this case
