### ISSUE TITLE
Adding ICE Candidate while signaling state is `have-local-offer` causes exception

### ISSUE THREAD

**Issue by xdumaine** [otalk/RTCPeerConnection#67]
I'm running into an error where I'm receiving an ice candidate prior to receiving the remote description (i.e., jingle transport-info before jingle session-accept). The error is occurring here. It could be avoided by adding another check to return if signaling state is `have-local-offer`. it's a crazy race condition with the xmpp server that's causing these to come in out of order, and could set me up for missing that candidate though... thoughts @fippo?

https://github.com/otalk/RTCPeerConnection/blob/master/rtcpeerconnection.js#L246

**Comment by fippo** [comment]
i'm afraid that fix will drop candidates without proper logging. We've had that error before and it was _very_ hard to debug

**Comment by xdumaine** [comment]
@fippo Updated to log and cache of the early updates until later. Let me know what you think, and I'll add tests for this.
