### ISSUE TITLE
two peerconnections share the same underlying connection

### ISSUE THREAD

**Issue by contra** [otalk/RTCPeerConnection#8]
Test case:

- User A connects to User B
- User A closes, PeerConnection is closed now
- User A attempts to connect to User B

```
Uncaught InvalidStateError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': The RTCPeerConnection's signalingState is 'closed'. 
```

super weird, still trying to dig around but I've compared references all the way down and it doesn't seem like any of the libraries are responsible

Chrome 35.0.1916.114 on OSX

**Comment by tommoor** [comment]
Hitting the same issue, after closing a peer connection instance a new one seems to have state closed. Will investigate.

**Comment by tommoor** [comment]
Note: My issue was due to an old peer connection reference still receiving events from the signalling lib. @contra yours is likely similar.

**Comment by fippo** [comment]
let me know if that isn't the case

**Comment by contra** [comment]
I tested the old code again with update modules and it quit happening. Something must have fixed it :question:
