### ISSUE TITLE
Nothing happens after offer/answer cycle finishes

### ISSUE THREAD

**Issue by peacemakr** [otalk/RTCPeerConnection#82]
I successfully managed to complete the offer/answer cycle between 2 clients. However, I don't see any relevant events (*streams) being triggered after that. 

I also have a wildcard event catcher that is catching undocumented events like "iceConnectionStateChange" etc and I also noticed the offer/answer events get called on PeerConnection.

I'm also running PC.handleAnswer on answer.

What could be wrong?

**Comment by peacemakr** [comment]
I don't see any errors and also seeing the regular communication pattern
This is what I found in caller's browser
```
12/15/2016, 4:34:13 PM	
createOffer
12/15/2016, 4:34:13 PM	
createOfferOnSuccess
12/15/2016, 4:34:13 PM	
setLocalDescription
12/15/2016, 4:34:13 PM	
signalingStateChange
12/15/2016, 4:34:13 PM	
setLocalDescriptionOnSuccess
12/15/2016, 4:34:13 PM	
iceGatheringStateChange
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
onIceCandidate
12/15/2016, 4:34:13 PM	
setRemoteDescription
12/15/2016, 4:34:13 PM	
addIceCandidate
12/15/2016, 4:34:13 PM	
signalingStateChange
12/15/2016, 4:34:13 PM	
iceConnectionStateChange
12/15/2016, 4:34:13 PM	
setRemoteDescriptionOnSuccess
12/15/2016, 4:34:13 PM	
iceGatheringStateChange
12/15/2016, 4:34:13 PM	
iceConnectionStateChange
12/15/2016, 4:34:13 PM	
iceConnectionStateChange
```

**Comment by fippo** [comment]
there is no addstream anywhere so quite likely you're not sending any streams

**Comment by peacemakr** [comment]
and thats exactly what the problem is ... when do I add stream (at what event?) and where? the *stream events of PC are not emitted

**Comment by fippo** [comment]
you do it before calling createOffer (usually). See https://github.com/otalk/RTCPeerConnection/blob/master/test/basic.js#L40 in the tests

**Comment by peacemakr** [comment]
that was the missing piece of the puzzle :)

It should be mentioned somewhere in the documentation as well

I'm also noticing high CPU usage when the video starts, any ideas what it could be related to based on the output of webrtc-internals?

**Comment by peacemakr** [comment]
this issue can be closed but it'd be awesome to mention addstream() in docs
