### ISSUE TITLE
adapter.js

### ISSUE THREAD

**Issue by peacemakr** [otalk/RTCPeerConnection#87]
Do I need to include adapter.js before this lib or it comes with adapter.js? 

The latest adapter.js version is 3.2.0

**Comment by xdumaine** [comment]
adapter.js is listed as a dependency in the package.json.

**Comment by peacemakr** [comment]
Thats news to me as in most cases docs mention script tags to use, so I never looked inside package.json.

here is the list of dependencies:
```
  "dependencies": {
    "lodash.clonedeep": "^4.3.2",
    "sdp-jingle-json": "^3.0.0",
    "webrtc-adapter": "^3.1.0",
    "wildemitter": "1.x"
  },
```
A/c to your comment I must include all the above in <script> tags on my html page. 

However, I also found rtcpeerconnection.bundle.js. If I include this bundled file then I don't have to include the rest separately. Is this assumption correct?

**Comment by xdumaine** [comment]
webrtc-adapter is adapter.js. Yes, it currently gets bundled in the bundle. Include it separately if you don't use the bundle.
