### ISSUE TITLE
a method to confirm connection

### ISSUE THREAD

**Issue by sido420** [otalk/RTCPeerConnection#92]
Thanks for the library.

Is there a direct way to find out if a connection is closed or not?

Also, if the close event has been called, is it safe to assume the connection is completely dead and needs to be started again?

**Comment by xdumaine** [comment]
@sido420 You can use `connection.iceConnectionState` and to get change events `connection.on('iceConnectionStateChange', handleStateChange)`

ICE connection state changes can be a little confusing. Primarily, if the iceConnectionState is `closed` then it's completely dead. If it's `disconnected` then it could be temporary and recover.

**Comment by sido420** [comment]
Thanks.

just wanted to be doubly sure, does the "close" event already take care of checking iceConnectionState or do I have to do that separately?

**Comment by xdumaine** [comment]
@sido420 looking at the code, it appears that `close` is only emitted when you explicitly close the connection. If it's closed on the remote end or due to a connection failure, I don't think the close event would be emitted. I'd use `on('iceConnectionStateChange', handleStateChange)` to be sure.

**Comment by sido420** [comment]
Thanks @xdumaine.

Perhaps, we should add that check to whatever code triggers "close" on PeerConnection??

**Comment by fippo** [comment]
don't call close() twice?

**Comment by sido420** [comment]
@fippo not sure what you mean
we can make sure we're not closing an already close peer connection or put the call inside a try-catch
